import styles from "./Industries.module.css";

type Pillar = { title: string; body: string };

const BANKING_PILLARS: Pillar[] = [
  {
    title: "Transaction monitoring",
    body: "Real-time surveillance across cards, wires, ACH, SEPA, UPI, and crypto — with structuring, layering, and velocity detection out of the box.",
  },
  {
    title: "KYC &amp; KYB",
    body: "PEP, sanctions, and adverse-media screening with explainable risk scores and audit-grade evidence at every step.",
  },
  {
    title: "SAR &amp; STR drafting",
    body: "Investigation narratives generated by AI, reviewed by your analysts, filed regulator-ready in minutes — not days.",
  },
  {
    title: "Network &amp; graph intelligence",
    body: "Two-hop sanctions exposure, money-mule ring detection, and 12-hop funds tracing through shell layers.",
  },
];

const BANKING_STATS = [
  { value: "40–60", unit: "%", label: "Faster investigations" },
  { value: "95", unit: "%", label: "False-positive reduction" },
  { value: "Full", label: "FATF / FinCEN audit lineage" },
];

export default function Industries() {
  return (
    <section id="industries" className="section">
      <div className="container">
        <div>
          <div className="eyebrow">
            <span className="eyebrow-dot" />
            Built for banking
          </div>
          <h2 className="section-title">
            Purpose-built for the <em>compliance back office</em> of modern banks.
          </h2>
          <p className="section-lede">
            SqAId is designed around the specific pressures of banking compliance — high alert
            volume, layered investigations, multi-jurisdiction reporting, and the unforgiving
            audit standards of FinCEN, OFAC, and the FATF. Every feature exists because a
            compliance team asked for it.
          </p>

          <ul className={styles.pillarList}>
            {BANKING_PILLARS.map((p) => (
              <li key={p.title} className={styles.pillar}>
                <div className={styles.pillarBullet} aria-hidden="true">
                  →
                </div>
                <div>
                  <div
                    className={styles.pillarTitle}
                    dangerouslySetInnerHTML={{ __html: p.title }}
                  />
                  <p
                    className={styles.pillarBody}
                    dangerouslySetInnerHTML={{ __html: p.body }}
                  />
                </div>
              </li>
            ))}
          </ul>

          <ul className={styles.statRow}>
            {BANKING_STATS.map((s) => (
              <li key={s.label} className={styles.stat}>
                <div className={styles.statVal}>
                  {s.value}
                  {s.unit && <span>{s.unit}</span>}
                </div>
                <div className={styles.statLabel}>{s.label}</div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
