import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import HexLogo from "./HexLogo";
import { COMPANY_EMAIL, PRODUCTS } from "@/lib/nav-data";
import styles from "./Footer.module.css";
export default function Footer() {
    const year = new Date().getFullYear();
    return (_jsxs("footer", { className: styles.footer, children: [_jsxs("div", { className: `container ${styles.inner}`, children: [_jsxs("div", { className: styles.col, children: [_jsxs("div", { className: styles.brand, children: [_jsx(HexLogo, { size: 22, tone: "muted" }), _jsx("span", { className: styles.brandName, children: "SqAId" })] }), _jsx("p", { className: styles.tagline, children: "AI-native risk & compliance intelligence for financial institutions." }), _jsx("a", { className: styles.email, href: `mailto:${COMPANY_EMAIL}`, children: COMPANY_EMAIL })] }), _jsxs("div", { className: styles.col, children: [_jsx("h4", { className: styles.colTitle, children: "Products" }), _jsx("ul", { className: styles.list, children: PRODUCTS.map((p) => (_jsx("li", { children: _jsxs(Link, { to: `/products/${p.slug}`, children: [p.name, p.status === "soon" && _jsx("span", { className: styles.tag, children: "Soon" })] }) }, p.slug))) })] }), _jsxs("div", { className: styles.col, children: [_jsx("h4", { className: styles.colTitle, children: "Company" }), _jsxs("ul", { className: styles.list, children: [_jsx("li", { children: _jsx(Link, { to: "/#about", children: "About" }) }), _jsx("li", { children: _jsx(Link, { to: "/#industries", children: "Industries" }) }), _jsx("li", { children: _jsx(Link, { to: "/#contact", children: "Contact" }) })] })] }), _jsxs("div", { className: styles.col, children: [_jsx("h4", { className: styles.colTitle, children: "Reach" }), _jsxs("ul", { className: styles.list, children: [_jsx("li", { children: "Tampa, Florida \u2014 HQ" }), _jsx("li", { children: "Pune, India \u2014 Operations" }), _jsx("li", { children: "Innovation Centers \u00B7 USA & India" })] })] })] }), _jsx("div", { className: "container", children: _jsxs("div", { className: styles.bottom, children: [_jsxs("span", { children: ["\u00A9 ", year, " Sqaid LLC. All rights reserved."] }), _jsxs("ul", { className: styles.legal, children: [_jsx("li", { children: _jsx("a", { href: "#privacy", children: "Privacy" }) }), _jsx("li", { children: _jsx("a", { href: "#terms", children: "Terms" }) }), _jsx("li", { children: _jsx("a", { href: "#security", children: "Security" }) })] })] }) })] }));
}
